@baseUrl = http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados/
?limit=10
&offset=0
###
GET {{baseUrl}}/recados/2/
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "NOVO RECADO",
    "de": "Goku",
    "para": "Maria",
    "lido": false,
    "data": "2023-10-01T10:00:00.000Z"
  }
###
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "texto": "NOVO RECADO",
    "de": "Goku",
    "para": "Maria",
    "lido": false,
    "data": "2023-10-01T10:00:00.000Z"
  }
###
DELETE {{baseUrl}}/recados/2/