@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados.
GET {{baseUrl}}/recados/
?limit=10
&offset=0
### Exibe um recado existente.
GET {{baseUrl}}/recados/2/
### Cria um novo recado.
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Olá, este é um recado - Lucas",
    "de": "Goku",
    "para": "Maria"
  }
### Atualiza um recado existente.
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "texto": "NOVO RECADO - Lucas",
     "de": "Goku",
    "para": "Maria"
   
  }
### Deleta um recado existente.
DELETE {{baseUrl}}/recados/2/